### PR TITLE
Bosh trap refactor/security fix

### PR DESCRIPTION
**Pull request by Houlistonm**
Current implementation of multiple traps
```bash
trap 'rm -f ${ssh_key_path}' EXIT`
trap 'rm -f ${bosh_ca_path}' EXIT`
```
has the effect of the second trap replacing the first and allowing files to accumulate in /tmp.

Refactored so a single trap will remove both files on exit.

### CODE REVIEW

**Comment by edwardecook** [comment]
Same as #10 looks good but need to enable Pivotal CLA bot.

**Comment by pivotal-issuemaster** [comment]
@Houlistonm Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/hammer&pullRequestId=11) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Houlistonm Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/hammer&pullRequestId=11)!

**Comment by Houlistonm** [comment]
Thank you.

**Pull request merged**
