### PR TITLE
added BOSH_GW_USER, BOSH_GW_HOST, BOSH_GW_PRIVATE_KEY to bosh

### PR DESCRIPTION
**Pull request by Houlistonm**
Changes to close isssue #9

### CODE REVIEW

**Comment by edwardecook** [comment]
Hi @Houlistonm, looks good to me however I will need to enable the Pivotal CLA bot on this repo before I can accept the request. Apologies for the delay.

**Comment by Houlistonm** [comment]
Thanks, hit me up on pivotal.slack.com

**Comment by pivotal-issuemaster** [comment]
@Houlistonm Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/hammer&pullRequestId=10) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Houlistonm Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/hammer&pullRequestId=10)!

**Comment by edwardecook** [comment]
I slightly messed up and merged https://github.com/pivotal/hammer/pull/11 first which contained the changes for this PR so I'm just going to close this.

**Comment by Houlistonm** [comment]
Thanks.

**Pull request closed without merging**
